---
title: "PR_4"
author: "Arikova Kristina"
date: "2024-10-05"
format:
  md:
    output-file: "README.md"
editor: "visual"
---

Использование технологии Yandex Query для анализа данных сетевой активности

## Цель

1.  Изучить возможности технологии Yandex Query для анализа структурированных\
    наборов данных

2.  Получить навыки построения аналитического пайплайна для анализа данных с\
    помощью сервисов Yandex Cloud

3.  Закрепить практические навыки использования SQL для анализа данных сетевой\
    активности в сегментированной корпоративной сети

## Исходные данные

-   Компьютер

-   Яндекс Браузер

-   Сервисы Yandex Cloud, Yandex Query

## Общий план выполнения

1.  Используя сервис Yandex Query настроить доступ к данным, хранящимся в сервисе хранения данных Yandex Object Storage
2.  Проверить доступность данных в Yandex Object Storage
3.  Подключить бакет как источник данных для Yandex Query
4.  Решить аналитические задачи с помощью SQL запросов

## Содержание ЛР

### Шаг 1. Настройка Yandex Query

Настройка и подключение к общей организации Yandex Query выполенена на основе методичкеских указаний.

```{r}
print("Hello")
```

### Шаг 2. Настройка доступа к данным Yandex Object Storage

## Оценка результата

## Вывод
